# Generated by Django 4.1.3 on 2022-11-23 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField('Task', 'description', 'task'),
    ]

    
